### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [MOIMOB/drinkable#101]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

Could you please in the meantime tag your releases (have a look [here](https://help.github.com/articles/creating-releases/) and [here](https://blog.github.com/2013-07-02-release-your-software/) for some help), and attach a signed release apk to it, it would allow people without access to Google Play to download, install and then later update your app 👍

**Comment by anton-gustafsson** [comment]
Hi! I'm currently in the process of adding the app to fdroid. There in an active rfp in the gitlab repo. 

I will definitely look into adding apk included releases! 

Thank you submitting this issue

**Comment by Poussinou** [comment]
Link to the [RFP](https://gitlab.com/fdroid/rfp/-/issues/2200) for anyone interested.

There is some progress as far as I can see in the RFP :)

**Comment by kojid0** [comment]
The app is now available on f-droid

**Comment by Poussinou** [comment]
The app is [here](https://f-droid.org/packages/com.moimob.drinkable) on F-Droid for anyone interested.

**Comment by anton-gustafsson** [comment]
Thanks guys!
