### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by kojid0** [MOIMOB/drinkable#106]
I'd like to contribute to the app and am willing to translate it to German. If that's possible, please tell me how to start

**Comment by anton-gustafsson** [comment]
Thank you! I will add swedish translation and update README.md with a guide. I'll link the commit here when I'm done 

I use i18n for translations, you can see example under src/locales.

**Comment by anton-gustafsson** [comment]
I have now updated the README.md with a contribution guide. You can also check this [commit](https://github.com/MOIMOB/drinkable/commit/62df9b8f085a2d473406e3f9212ba95e30e9499a) out

**Comment by kojid0** [comment]
Thanks, I will do it soon and will let you know. I'm closing the issue since you've updated the README.md file :)
