### ISSUE TITLE
Contact developer: Send button not working

### ISSUE THREAD

**Issue by kojid0** [MOIMOB/drinkable#107]
When I hit the button to send you a message, nothing happens. It either doesn't work or you should implement a hint stating that the message has been successfully sent (and clear the form afterwards).

**Comment by anton-gustafsson** [comment]
Oh I see. The Google Play version works fine, so I think it has something to do with the f-droid build script. Will look into that

**Comment by anton-gustafsson** [comment]
Link [here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11843) for merge request on gitlab

**Comment by anton-gustafsson** [comment]
Works fine now!
