### ISSUE TITLE
Add possibility to rate drinks

### ISSUE THREAD

**Issue by kojid0** [MOIMOB/drinkable#108]
Add possibility to personally/locally rate drinks, e.g. by adding 1-5 stars or placing a box for comments, also for suggested changes about the amount of ingredients used.

**Comment by anton-gustafsson** [comment]
Thanks! @kojid0

**Comment by anton-gustafsson** [comment]
You will be able to rate cocktails in the latest version of the app (v1.14.0) 

It will be available on both fdroid and google play store asap

**Comment by kojid0** [comment]
Cool, thanks!
