### ISSUE TITLE
Possibility to add new ingredients?

### ISSUE THREAD

**Issue by krillin666** [MOIMOB/drinkable#113]
First off, congratulations for the app. It's really will made and the UI is very beautiful.

I noticed some ingredients are missing like *baileys* and *limoncello*. Could you add a feature for users to add ingredients ?
I assume these aren't in the database because there's probably no drink there with this ingredients already

Thank you for your time!

**Comment by anton-gustafsson** [comment]
Thank you! You're right, ingredients gets added from the cocktails.

Adding ingredients is already a feature in the app. It can be done in two ways. First in the menu when you are creating a cocktail, secondly under Ingredients -> Manage

Please let me know what you think of this user experience. Maybe I need to make it more clear somehow. 

Thanks for opening this issue!
