### ISSUE TITLE
The bottom bar

### ISSUE THREAD

**Issue by yephny** [MOIMOB/drinkable#119]
Are you happy with the new bottom bar? It feels like a debug version of the app, with only a tiny yellow outline around the buttons. Plus, it goes away when you tap somewhere else, so you can't see what page you're on. I'm not sure how difficult it'd be for you, but it might be a good idea to fill the icon of the active button with a color, and completely ditch the outline.

**Comment by anton-gustafsson** [comment]
Are you sure you are in the correct repo. The bottom bar looks like this.

![image](https://user-images.githubusercontent.com/22906905/196052749-490e050e-8e95-40a7-961d-1d563c4088e7.png)

Earlier like this:

![image](https://user-images.githubusercontent.com/22906905/196052829-3a2f272c-3119-48e9-a2e6-1108ad96f78b.png)

**Comment by yephny** [comment]
I downloaded 1.9.0 from F-Droid, this is what it looks like:

![img](https://a.pomf.cat/jwpgnk.png)

**Comment by anton-gustafsson** [comment]
The bottom bar is now updated in the latest release (1.10.1) on f-droid.

**Comment by yephny** [comment]
The yellow outline is still there.

**Comment by anton-gustafsson** [comment]
I think that the outline is some default focus for your browser.

 I can try to disable focus on the navbar.

**Comment by yephny** [comment]
The yellow outline is gone as of v.1.30.0.
