### ISSUE TITLE
Request: Sorting of "1 Missing Ingredient" list

### ISSUE THREAD

**Issue by xkns** [MOIMOB/drinkable#121]
The list of cocktails under Cocktails -> From Ingredients -> 1 Missing Ingredient could be much more useful if:

1. cocktails missing the same ingredient were grouped together
2. these groups were sorted by their size (e.g. a group of 5 cocktails missing gin would be shown above a group of 3 cocktails missing vodka)

This would make it much easier for users to decide which ingredient to buy next and to efficiently explore the recipe space provided by the app.

In that sense it might even be beneficial to show cocktails missing more than one ingredient if there aren't many/enough with just a single missing ingredient. But that's probably stuff for a new issue.

**Comment by anton-gustafsson** [comment]
Hi! That you for opening this issue. 

I fully agree with you, sorting the 1 missing ingredient list will have alot benefits. I will add this is an upcoming release.

I have though about displaying cocktails with two missing ingredients. But with the sorting rules above I do not know how it will work out.

**Comment by anton-gustafsson** [comment]
This is now avaliable in the latest release on f-droid

**Comment by xkns** [comment]
Wow that was quick!

Thank you very much :)
