### ISSUE TITLE
Infos about translations and cocktail

### ISSUE THREAD

**Issue by RAMAR-RAR** [MOIMOB/drinkable#128]
It will be translationable the ingredients and instructions(in different files) in the future(maybe on crowdin or weblate)?

Who is the current main source of the cocktails?

**Comment by anton-gustafsson** [comment]
Hi! There is a guide on how to contribute with translation in the README.md file. There is a json file for each language

The source of the cocktails is mostly thecocktaildb, own creations and from other submitting within the app.

**Comment by RAMAR-RAR** [comment]
https://github.com/MOIMOB/drinkable/commit/3cdf0a5926f9982b1cc60bd82bf8b79fd64a0733

https://github.com/MOIMOB/drinkable/commit/baf5127771318073bbb24da67195bbc6c87e9112

**Comment by nautilusx** [comment]
@anton-gustafsson 
Thanks for your great app.

Can you please use weblate.org for the translation. It makes translation much easier for non-developers. It's free and open and for free apps, like yours, it's also free and gratis.

https://weblate.org/hosting/

**Comment by anton-gustafsson** [comment]
@RAMAR-RAR Thank you for the commits!

Could you please create a Pull request? That way you will get added to the contribute list

**Comment by anton-gustafsson** [comment]
@nautilusx 
Thank you! I will definitely look into weblate

**Comment by Korb** [comment]
> [@nautilusx](https://github.com/nautilusx) I will definitely look into weblate

Judging by the lack of links to the translation project here and in `README.md`, I conclude that there is none yet.

If (FOSS) Weblate isn't quite right for you, consider using **Crowdin** or **Transifex** (both proprietary but free for FLOSS projects).
