### ISSUE TITLE
Orange Liqueur and Triple Sec are interchangeable in many drinks

### ISSUE THREAD

**Issue by Heff2010** [MOIMOB/drinkable#135]
Triple Sec and orange liqueur are interchangeable in many drinks. And in margaritas, Triple Sec is preferred. In my opinion, there should be a way to combine them. 

If not, a way to tweak recipes would also suffice so I can swap them myself.

**Comment by anton-gustafsson** [comment]
Yes! I'll want to combine them. Just need to figure out how

I could remove triple sec and just use orange liqueur, but I don't think the experience would be that great. 

Tweaking recipes is a great feature. Thanks!

**Comment by anton-gustafsson** [comment]
There is now a version  (v1.17.0) that combines interchangeable ingredients. It should be avaliable on Google Play Store and F-droid in a couple of days.
