### ISSUE TITLE
Ability to add custom mesurements and enhancing "instructions" when creating cocktails 

### ISSUE THREAD

**Issue by JustAnotherSupporter** [MOIMOB/drinkable#144]
Hello there
First and foremost I would like to praise the app which has a very intuitive design and a good amount of drinks pre-made from the get-go. 

I have the following suggestions that might improve the app:
1) I'm unable to set my own measurements when creating a drink (lack the option to set grams, sprigs, halves and so on).

2) the "instructions" tab when creating a drink doesn't respect line breaks, which would make reading the different steps easier.

3) Doesn't allow setting multiple categories and creating ones own categories (E.g. Setting "cocktail" and creating and setting the category "IBA").

**Comment by anton-gustafsson** [comment]
Thank you for the kind words and all the improvement suggestions 

Line breaks for the instructions is probably an easy fix and should not take long

I will have to refine and try out the other suggestions. Thanks!

**Comment by anton-gustafsson** [comment]
Line breaks is now supported in the instructions section. (v1.12.0)

**Comment by anton-gustafsson** [comment]
Multiple categories is now available using tags 👍🏼 Closing this issue!
