### ISSUE TITLE
Export/Import function

### ISSUE THREAD

**Issue by SamTada** [MOIMOB/drinkable#152]
Any way to add a Export/Import function in Settings to backup your recipes and ingredients to a file, should you need to reinstall the app?

**Comment by anton-gustafsson** [comment]
There is currently no way to export/import any data in the app. But it is a great feature that I will add in the future. Thanks

**Comment by sbennett18** [comment]
Not totally sure how it might be helpful or not, but there's this. Could be cool to export to this format.
https://cooklang.org/

**Comment by anton-gustafsson** [comment]
@sbennett18 Cool! Thank you for the link

**Comment by Lugrim** [comment]
The model of cooklang is very much different from the one used by Drinkable. As of today, I see different ways to solve the current issue:

1.  Change the model of Drinkable to match the one of Cooklang
    - :+1: Cooklang is a great way to store recipes and would allow lot of new features in the future
    - :+1: Drinkable would match an external format and be more easily interoperable with other cooking and cocktail software
    - :-1: Would require a lot of work of redesign in the backend part of the code
2. Add a compatibility layer with cooklang
    - :+1: Drinkable would still be somewhat interoperable with some other software
    - :+1: Does not require to change all existing code of the app
    - :-1: There will be a lot of data loss and results will be clunky
3. Add a way (our own way) to serialize current model of Drinkable
    - :+1: Fast and easy to implement
    - :-1: Will be a custom made format, compatible with nothing else

Any opinion on this? I can take a look at option 1 that look the best to me (I'm really looking forward for features that can be enabled with cooklang), but it will require quite a bit of work that I probably won't be able to do alone.

**Comment by anton-gustafsson** [comment]
@Lugrim Thank you for sharing all of the ideas above 👍🏼 

I would love to use a more used external format for storing the recipes. As you pointed out It will improve the experience for Drinkable and also maybe other apps. 

I do however see an issue with converting to cooklang as it only supports english as of now. As you can read in [this proposal](https://github.com/cooklang/spec/pull/86/files)

Could you please describe the features that cooklang would enable? Maybe we can implement them anyways?

**Comment by Lugrim** [comment]
Three examples that come to my mind are:
- Having directly the quantities in the recipe (in case an ingredient appears twice) while still being able to generate an ingredient list
- Timers in recipe, could be started with a single tap on text
- Metadata (source, special warnings, ...)

Sadly, the proposal you linked looks pretty dead, I'm gonna try to bump it a bit

**Comment by Lugrim** [comment]
Three examples that come to my mind are:
- Having directly the quantities in the recipe (in case an ingredient appears twice) while still being able to generate an ingredient list
- Timers in recipe, could be started with a single tap on text
- Metadata (source, special warnings, ...)

Sadly, the proposal you linked looks pretty dead, we can try to bump it.
We could still use a workaround by using cooklang while either adding some kind of associative table to make different grammatical cases match or accepting the recipes to be grammatically inaccurate (and using only singulars).

**Comment by BradNut** [comment]
This would also be nice to have. Just wondering if there's been any progress on this? 🙂

**Comment by Lugrim** [comment]
> This would also be nice to have. Just wondering if there's been any progress on this? 🙂

I guess we are waiting for updates on cooklang/spec#86 ? It would be great to switch on a cooklang model IMO, but yet, we'd have localization problems

**Comment by anton-gustafsson** [comment]
I guess we could do export /import functionality with a simple JSON file. I'm not really sure where the user would like to store it though.

**Comment by C0smin** [comment]
Would be great to be able to export/import in the current format also, is there any workaround for that?

**Comment by anton-gustafsson** [comment]
It would be great! I could implement it. Do you have any idea for where to store the data?

**Comment by C0smin** [comment]
Hey @anton-gustafsson, I don't have great technical knowledge on how that would be implemented here, but in my mind there would be no other storage location. When user wants to export a backup, create a json and ask the user where to store it (presumably defaults to downloads). Import would be the reverse action.
I would also presume that this would backup my _"My Bar"_ and when importing maybe the question would be what to do with the imported data, overwrite _<bar-name>_ if it exists or update it (update being the more technically complicated aspect), but I would suggest this is a later expansion on the feature rather than making this one too big. Hope i make sense 😅

**Comment by anton-gustafsson** [comment]
@C0smin Yeah it made a lot of sense 😄 

I think it can be relative easy to implement using https://capacitorjs.com/docs/apis/filesystem

**Comment by anton-gustafsson** [comment]
@C0smin 
#505

**Comment by C0smin** [comment]
This is great news! Thank you @anton-gustafsson ! 😄
