### ISSUE TITLE
Add translation service

### ISSUE THREAD

**Issue by PanderMusubi** [MOIMOB/drinkable#160]
Add a (free) translation service such as Weblate in order to support more languages and more easily maintain current translations. Weblate is free for FOSS by the way.

**Comment by aha999** [comment]
i agree with Weblate, as it's open source itself and it has a free plan for foss projects.

it can automatically push changes and it has a nice widget that shows progress percentage of languages.

**Comment by anton-gustafsson** [comment]
Thanks guys. I will check out Weblate
