### ISSUE TITLE
Add mocktail

### ISSUE THREAD

**Issue by Rexadev** [MOIMOB/drinkable#161]

**Comment by anton-gustafsson** [comment]
Hi! Adding mocktails to the app sounds great. Could you please provide some more information on how you(as a user) would like it in the app, filter options? some other mocktail features? 

 Also is there some specific mocktails that you like to be included?

**Comment by Rexadev** [comment]
Mocktail or Cocktail should be the first filter a user is asked to apply.

**Comment by anton-gustafsson** [comment]
Mocktails will be avaliable in the next version of the app (v1.17.0). So probably on Google Play Store and F-droid in a couple of days

**Comment by Mingo-coder** [comment]
Fantastic app and very easy to use. Could you add a mocktail tab at the bottom?

**Comment by anton-gustafsson** [comment]
@Mingo-coder Great idea! The app could you you the options
- show both cocktails & mocktails
- show only cocktails
- show only mocktails

If option 'show only mocktails' is selected that can change the navigation tab to mocktails

I'm open for PRs if you are interested😄

**Comment by anton-gustafsson** [comment]
@Mingo-coder I added this feature here #583
