### ISSUE TITLE
Feature request: search cocktails by ingredient

### ISSUE THREAD

**Issue by muusik** [MOIMOB/drinkable#198]
Hi! First off, thanks for the great app. It's the perfect way of approaching cocktail mixing for me, especially the "1 Missing Ingredient" list.

I am currently looking at a bottle of Maraschino liqueur and wondering what I could use it in. This feels like a use case Drinkable could cover, but currently it doesn't. Search under All Cocktails doesn't appear to cover ingredients, only recipe titles, and there doesn't appear to be a way to click on an ingredient and see all the cocktails it is used in. Either approach would work for my use case, should it amuse you to implement it. (Sorry, no pull request from me at this time.)

Either way, thank you again for the useful app, and best of luck.

**Comment by anton-gustafsson** [comment]
Thank you! I'm glad you enjoy the app.

I think both options would work and I'd like to implement them both.

I will definitely add an option to filter cocktails by a specific ingredient. Would that cover your use cases? 

Then to click and open a ingredient is a bigger feature that I have plans for later. But when I implement it I will add a list of cocktails using that ingredient.

Thank you again for opening this issue. Please give it a rating in the play store if you are using the Google Play version

**Comment by muusik** [comment]
Indeed, filtering by ingredient would cover it perfectly.

I'm using the f-droid version and currently not using Google Play Services, thus not able to give a review. But I'm definitely recommending Drinkable to friends.

**Comment by anton-gustafsson** [comment]
Filtering by ingredient is now avaliable in the latest version of the app on f-droid (v1.18.0)

Please let me know what you think of it!

**Comment by muusik** [comment]
Yes, I can now use Drinkable to answer "I wonder what I could use this in" to my heart's content. This has been amazingly responsive, thank you again.
