### ISSUE TITLE
Material You integration

### ISSUE THREAD

**Issue by Mr-Bajs** [MOIMOB/drinkable#229]
Nice app, but would be great if it where integrated with the Material You theming for Android for a cleaner look.

**Comment by anton-gustafsson** [comment]
Hi! Great idea 💡 

But unfortunately I don't think this is possible to implement into a webview. This app is built using capacitor js. 

I could add more themes to the app for further customization. Currently only dark and light mode is avaliable.

**Comment by ThatOneCalculator** [comment]
You can use this plugin: https://github.com/tanishqmanuja/capacitor-plugin-monet
