### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by Michele64** [MOIMOB/drinkable#253]
it would be nice to have the favorites displayed either on home as separate row or as separate page in the cocktais tab..
just a suggestion to your really nice and helpful and interesting app 😊

**Comment by anton-gustafsson** [comment]
Hi! Thank you for the suggestions!

Currently you can use the filter and select 'Show only Favorites'. But I agree, there should be some sort of widget on the home page that displays your favorites

**Comment by anton-gustafsson** [comment]
Any thoughts on this?
I think it would be great with another button on the right of it. Used for quick navigation.

![image](https://user-images.githubusercontent.com/22906905/234495232-89492f19-062c-4cb9-b1cd-fddc6adc8f0d.png)

If button is pressed you will be taken to this page with filter 'Show only Favorites' selected

![image](https://user-images.githubusercontent.com/22906905/234495802-1dc05ce8-cc26-41b8-8f9c-66ad98e66592.png)

**Comment by Michele64** [comment]
more like this:

![Screenshot_20230426-112419](https://user-images.githubusercontent.com/13287876/234540699-a02aea65-914f-4419-bfca-58437ec54703.jpg)
![Screenshot_20230426-112425](https://user-images.githubusercontent.com/13287876/234540741-0d809ed7-a834-424e-8eb1-f5f972a8d47b.jpg)

**Comment by anton-gustafsson** [comment]
I will make a new release(1.24.0) close to what I posted above. It should be available on Google Play Store And fdroid in a couple of days.

The app had a favorites tab before but i felt It was unnecessary to have when the filter button was added. Maybe I'm wrong. I'l leave this issue open for a while for more input.
