### ISSUE TITLE
Inclusion of all IBA Cocktails

### ISSUE THREAD

**Issue by anton-gustafsson** [MOIMOB/drinkable#277]
Drinkable should include all cocktails listed in the International Bartenders Association (IBA). The IBA sets industry standards for cocktail recipes.

https://thebarcabinet.com/recipes/international-bartenders-association-recognised-cocktails/

- [ ] - Trinidad Sour
- [x] - Barracuda 
- [x] - Bloody Mary
- [x] - Caipirinha
- [x] - Cosmopolitan
- [x] - Espresso Martini
- [x] - Gin Fizz
- [x] - Horse’s Neck
- [x] - Last word
- [x] - Margarita
- [x] - Mojito
- [x] - New York Sour
- [x] - Paradise
- [x] - Porto Flip
- [x] - Sea Breeze
- [ ] - Spicy Fifty
- [x] - Tipperary
- [ ] - Vieux Carrè
- [x] - Alexander
- [x] - Bee’s Knees
- [x] - Boulevardier
- [x] - Casino
- [x] - Cuba Libre
- [ ] - Fernandito
- [x] - Golden Dream
- [ ] - Illegal
- [ ] - Lemon drop Martini
- [x] - Martinez
- [x] - Monkey Gland
- [ ] - Old Cuban
- [x] - Penicillin
- [ ] - Ramos Fizz
- [x] - Sex on the Beach
- [x] - Spritz
- [x] - Tommy’s Margarita
- [x] - Whiskey Sour
- [x] - Americano
- [x] - Bellini
- [x] - Bramble
- [x] - Champagne Cocktail
- [x] - Daiquiri
- [x] - French 75
- [x] - Grasshopper
- [x] - Irish Coffee
- [x] - Long Island Ice Tea
- [x] - Mary Pickford
- [x] - Moscow Mule
- [x] - Old Fashioned
- [x] - Pina Colada
- [x] - Russian Spring Punch
- [x] - Sidecar
- [x] - Stinger
- [x] - Tuxedo
- [x] - White Lady
- [x] - Angel Face
- [x] - Between the Sheets
- [ ] - Brandy Crusta
- [x] - Clover Club
- [x] - Dark ‘n’ stormy
- [x] - French Connection
- [ ] - Hanky Panky
- [x] - John Collins
- [x] - Mai-Tai
- [x] - Mimosa
- [ ] - Naked and Famous
- [x] - Paloma
- [x] - Pisco Sour
- [x] - Rusty Nail
- [x] - Singapore Sling
- [ ] - Suffering Bastard
- [ ] - VE.N.TO
- [x] - Yellow Bird
- [x] - Aviation
- [x] - Black Russian
- [ ] - Canchanchara
- [x] - Corpse Reviver 
- [x] - Dry Martini
- [x] - French Martini
- [x] - Hemingway Special
- [ ] - KIR
- [x] - Manhattan
- [x] - Mint Julep
- [x] - Negroni
- [x] - Paper Plane
- [ ] - Planter’s Punch
- [x] - Sazerac
- [ ] - Southside
- [x] - Tequila Sunrise
- [x] - Vesper
- [ ] - Zombie

**Comment by anton-gustafsson** [comment]
Missing cocktails:

### Unforgettable Cocktails
- Angel Face
- Aviation
- Bacardi
- Between The Sheets
- Casino
- Clover Club
- Derby
- Gin Fizz
- John Collins
- Mary Pickford
- Monkey Gland
- Paradise
- Planters Punch
- Porto Flip
- Ramos Gin Fizz
- Rusty Nail
- Sazerac
- Stinger
- Tuxedo
- White Lady

### Contemporary Classic Cocktails
//TODO

### New Era Cocktails
//TODO

**Comment by anton-gustafsson** [comment]
On this page
https://iba-world.com/category/iba-cocktails/


Run this script to get all the names
let nodeList = document.getElementsByClassName("et_pb_salvattore_content")[0].querySelectorAll('h3 > a');
let names = [...nodeList].map(x => x.text);
console.log(names);

**Comment by anton-gustafsson** [comment]
Yes! I could write a guide on how to contribute with new recipes, will add to README.md

**Comment by Neriderc** [comment]
Guide to contributing recipes would be good! 

There are a bunch of recipes that need adjustments (especially where they expect ingredients not covered in the ingredients list!). Having a guide for contributing recipes would be helpful for this.

**Comment by anton-gustafsson** [comment]
@Neriderc I have updated the readme with guides to add new ingredient and cocktails. Would be great if anyone tried it out and provided feedback if I need to be more in depth 🚀

**Comment by Neriderc** [comment]
@anton-gustafsson I think there's enough information there for me. Probably anyone that's going to do a pull request will find that you've provided enough info.

Maybe one suggestion is a brief overview of the structure. To add a cocktail, the ingredients are added in one file, the amounts are added in another, the display name of the cocktail is in a different file, and the instructions are in yet another. Maybe a short intro at the start of the Contributing section to explain this would help?

**Comment by anton-gustafsson** [comment]
@Neriderc Thank you! I agree
