### ISSUE TITLE
Add "close ingredients" functionality

### ISSUE THREAD

**Issue by Epholys** [MOIMOB/drinkable#355]
Hello!

I have an idea for a new functionality: adding an option to account for missing ingredients by checking if there are similar alternatives available.

For instance, if a cocktail recipe requires lime juice, but the user only has lemon juice, this feature would still suggest the cocktail as the two ingredients are quite similar.

Of course, this is just a proposal for a "nice to have" feature, from my point of view 😄.

**Comment by anton-gustafsson** [comment]
Hi! 

Great idea. This is already possible on a ingredient level. 

Here is two examples:
Required: Lime Juice
Accepted: Lime Juice, Lime

Required: Orange Liqueur
Accepted: Orange Liqueur, Triple Sec, Cointreau

![image](https://github.com/MOIMOB/drinkable/assets/22906905/27d47784-90b7-49cf-9b05-bb0d0569ffec)

In your example, I'm not that sure you could always substitute lemon juice for lime juice and vise versa. But the feature exist and if something is 'almost' the same i think it should be added as a substitute ingredient. 

If there a use case where users should can set  their own substitutes? My first thought is that is should be standardized and for everyone using the app. 

Love to hear your thoughts!

**Comment by Epholys** [comment]
Oh, I just realized I completely missed this feature! I might have been too focused on the lime/lemon issue and didn't notice that it was already implemented.

Allowing users to set their own substitutes could work, but it might make the app a bit clunky to use. Interestingly, you can already kind of handle this by saying you have lemon and lime, even if you have only on of those. It's not using the app as intended, but it still works!

Another option could be to have several levels of "fuzziness": starting with the default level (level 1) that includes common substitutions like triple sec and cointreau. Then, you could offer a level 2 where users can substitute lemon and lime. However, implementing this might require a lot of work and careful consideration to decide which ingredients can be combined at each level of fuzziness.

Anyway, my original remark is already implemented, so if you believe the app is working fine as it is, you can consider this issue closed. If you have any other ideas or feedback in the future, feel free to share them! 😄

**Comment by anton-gustafsson** [comment]
Thank you for the input! I will close this
