### ISSUE TITLE
Add an option to translate using lingva 

### ISSUE THREAD

**Issue by Turhvjbufv** [MOIMOB/drinkable#356]
1.Because lingva pulls from Google it's usually very accurate 

2. Not everyone has the time or the knowledge to translate the app's ingredients and such so it would be easier to have an option to translate ingredients using some tool

**Comment by anton-gustafsson** [comment]
Thank you! It seems like a nice tool

Do you think that linking to it from the README file is enough, or did you have something else in mind

**Comment by Turhvjbufv** [comment]
I think add an option in settings to set the language you want to translate to and then in the README file there will be a translation button
