### ISSUE TITLE
Upload an apk

### ISSUE THREAD

**Issue by w9925** [MOIMOB/drinkable#362]
Please add the apk file for the download direct from git

**Comment by anton-gustafsson** [comment]
@w9925 Great Idea. Where should I put it? Under Github Releases?

**Comment by anton-gustafsson** [comment]
F-droid lists the apk already and Obtainium supports F-droid as an app source. 

So this should already work? Or is it something I'm missing?

**Comment by GenericMale** [comment]
Yes it works but some people prefer to get the apk directly from github.
F-droid signing everything with their own key is a bit controversial.
This is a very minor issue though.

**Comment by ChrisLane** [comment]
I would also prefer getting APKs from GitHub. F-Droid can be a bit slow to get releases into their repos.
