### ISSUE TITLE
multiple Ingridiense lists

### ISSUE THREAD

**Issue by Qreed213** [MOIMOB/drinkable#368]
I have some ingridionse home

So when i go to  frends house ther  are diffrent dlinks i can mixs sints i don't bring all my ingrediesne.

ther whud be awsome to have difflent lists if you are home, at a frend or enjoying  moktail at work. And store them separat.

love the app tonk you

**Comment by anton-gustafsson** [comment]
Great idea! Would be pretty simple to implement. I will take a look at this

**Comment by anton-gustafsson** [comment]
This will be available in v1.37.0 🚀

**Comment by Qreed213** [comment]
Tank you
that is awsome.

**Comment by Qreed213** [comment]
I use f-droid.

what is the expected update releas  on F-Droid after you roole updates?

**Comment by anton-gustafsson** [comment]
Should be available soon! usually it takes 1-3 days
