### ISSUE TITLE
Bugg inn favorites after chaging filters 

### ISSUE THREAD

**Issue by Qreed213** [MOIMOB/drinkable#391]
When i navigate

- home-favorites-filters

- remove ((show only favorites))
- and add some other filter

- choose a drink and go back

The bugg has now added back ((show only favorites))

https://github.com/MOIMOB/drinkable/assets/36892515/e9678821-3ca8-40b2-bfb0-6a08d9793504

**Comment by anton-gustafsson** [comment]
Hi! Thank you for reporting this

Will release a fix shortly

**Comment by anton-gustafsson** [comment]
#393

**Comment by anton-gustafsson** [comment]
This will be fixed in version 1.39.1 🚀

**Comment by Qreed213** [comment]
Can i choone label on the ticket ((bugg))

**Comment by Qreed213** [comment]
Can i choone label on the ticket ((bugg))

**Comment by anton-gustafsson** [comment]
I think you should be able to do that :)
