### ISSUE TITLE
Remember last profile.


### ISSUE THREAD

**Issue by Qreed213** [MOIMOB/drinkable#395]
It whuld be nice for the application to remember last profile used. 

the app always fall back to the first made user profile.

Nott a bigg deal but a enhancement.

love the app. Ty

https://github.com/MOIMOB/drinkable/assets/36892515/4942ac26-56b3-4008-862d-b1217cf56a99

**Comment by anton-gustafsson** [comment]
Yes I agree. The app should use last bar selected when restarted

Thank you for the improvements!

**Comment by Qreed213** [comment]
Or abillity to choose profil on app start.
