### ISSUE TITLE
Add inglidience from recepy

### ISSUE THREAD

**Issue by Qreed213** [MOIMOB/drinkable#396]
abillity to add missing ingrudionce to a user list if it is showen ass missing inn the recepy.

![Screenshot_2023-10-14-19-50-39-34_8c373e0d20e6fa370027827b7bd7deb7.jpg](https://github.com/MOIMOB/drinkable/assets/36892515/c573b5c9-ab1b-47b9-aa23-072adea4b6c8)

**Comment by anton-gustafsson** [comment]
Let me know if I understand correctly. A user checks out the recipe above an remember that they do have Brandy at home. Then a user should be able from here to add it into its ingredient list? 

Should work both ways. Add and delete

Do you have an idea on how to display this in the app? 😄

**Comment by Qreed213** [comment]
Hold for a menue to remove or add to the selected bar.


today single tapp is add red line over a  ingledience. 

so hold shuld show a message that
 The item wilbe added.



![bar tabb.png](https://github.com/MOIMOB/drinkable/assets/36892515/67307c44-17b3-4723-83a9-33bc361e1d55)

**Comment by Qreed213** [comment]
Hold for a menue to remove or add to the selected bar.


today single tapp is add red line over a  ingledience. 

so hold shuld show a message that
 The item wil be added /removed.

higliting the ingredience and using the orginal posission of it shuld not interfare with long ingredience name when the add text is abow.


![bar tabb.png](https://github.com/MOIMOB/drinkable/assets/36892515/67307c44-17b3-4723-83a9-33bc361e1d55)

**Comment by Qreed213** [comment]
Maby a choice of ((bar  / user)) shuld be used / showen

![signal-2023-10-20-18-04-40-563.jpg](https://github.com/MOIMOB/drinkable/assets/36892515/a9cdd018-297f-44f5-9b89-6e5aa70a2591)

**Comment by anton-gustafsson** [comment]
@Qreed213 Thank you for the screenshots! Great feature I will try to implement something like this. Will try to update on the progress in this issue 🚀

**Comment by Qreed213** [comment]
im working off pocket paint on Android so this is a rough picture and idea. sorry for the terrible english.

**Comment by anton-gustafsson** [comment]
I'm just trying stuff out for now. Any feedback on this? @Qreed213 😄 

![image](https://github.com/MOIMOB/drinkable/assets/22906905/7aa51dca-cef6-4d66-bc72-ac87e6015c86)

**Comment by Qreed213** [comment]
Super cool.
This looks good 

Im no coder so i dont konw how this is to implement.

i was thinking that hold down on ingridience chuld do multiple things.
like
= Add/ remove to/from bar 
= Coppy ingridience (( to coppy was something that i was trying to do sints i wanted to paste it into shoppinglist and a serch engen))



but ther shuld be a way to se what bar/user it is worked on (( if i scroole way down i dont se my 4B)) but i alsow se a possible problem if the ingredience is SUEPR LONG and the BAR / USER name is super loang.

**Comment by Qreed213** [comment]
i have more idea but coppy shuld be easy :s

![bar inglidience.png](https://github.com/MOIMOB/drinkable/assets/36892515/f3044989-ebab-47ce-9383-3d8c041b408a)

**Comment by anton-gustafsson** [comment]
Great ideas! I will create a release for add/remove from bar and copy ingredient name to clipboard.

Add ingredient directly to shopping list would be awesome, it is a little more work so I will release this in 2 parts. 

Thanks you and Cheers!

![image](https://github.com/MOIMOB/drinkable/assets/22906905/07fff887-7b48-486c-99e8-ac0265089832)

**Comment by anton-gustafsson** [comment]
Adding the same functionality if you long press on a cocktail. It should let you add/remove from favorites 

![image](https://github.com/MOIMOB/drinkable/assets/22906905/79aa1ce4-e4f0-4284-80cb-03a970301741)

**Comment by Qreed213** [comment]
Unintended bugg / unwanted.

the hold add/ remove and copy wil be triggerd while ''scrolling''

https://github.com/MOIMOB/drinkable/assets/36892515/06d67e3a-4c89-4844-bf94-8009072f7edf
