### ISSUE TITLE
Obsolete dependencies

### ISSUE THREAD

**Issue by Mr-Bajs** [MOIMOB/drinkable#416]
In the install app dependencies test shows this:

> _Run npm ci
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
> npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
> npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
> 
> added 1813 packages, and audited 1814 packages in 28s
> 
> 226 packages are looking for funding
>   run `npm fund` for details
> 
> 7 high severity vulnerabilities
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> 
> Run `npm audit` for details._

So is the app are using old obsolste depenencies, if so then it should be updated.

**Comment by anton-gustafsson** [comment]
Thank you for reporting this! It is now resolved in the main branch 

Cheers!
