### ISSUE TITLE
Scroll hold bugg.

### ISSUE THREAD

**Issue by Qreed213** [MOIMOB/drinkable#420]
Scroll and hold will trigger the new feature: add/remove/copy ingredienc. 

This doesn't happen to read line ingredients when fast scroll.

https://github.com/MOIMOB/drinkable/assets/36892515/2273351a-29c7-418e-b87d-27b676306e4b

https://github.com/MOIMOB/drinkable/issues/396#issuecomment-1783164519

**Comment by anton-gustafsson** [comment]
I see the issue. I will increase the long press timing for now until I have a better solution.

**Comment by Qreed213** [comment]
But it don't happen for read line.


or make dubble tapp?

**Comment by anton-gustafsson** [comment]
How do you think the current solution is working? Now it is a really long press before the dialog opens

**Comment by Qreed213** [comment]
After testing it it whud me nice to have feead back when it starts to registrer.

I have had some wrong placement and was wating for the dialog but it never happend. 

is dubble tapp pluss hold a possibillity or add a wibration 250 ms after enisiating it.
the vibration is alreddy existing when loand hold on the drink picture in all coctails.

(( loang hold dont work if preformed emidietly after opning a drink se video))

https://github.com/MOIMOB/drinkable/assets/36892515/c14bd76c-d7cb-4f78-83e8-18cc27b894f8
