### ISSUE TITLE
bugg with Bar/user managment

### ISSUE THREAD

**Issue by Qreed213** [MOIMOB/drinkable#424]
I wil poste more tekst later.

https://github.com/MOIMOB/drinkable/assets/36892515/d216fb05-0975-4cc6-830b-6b2a0331262d

**Comment by Qreed213** [comment]
the bar/user is wiped and re weigthen over bye a newer user.

users are not rememberd after a user change is made.

i dont really got anny good explenation.

**Comment by anton-gustafsson** [comment]
Thank you for the recordings, I will look into this

**Comment by Qreed213** [comment]
<3
