### ISSUE TITLE
Price per cocktail

### ISSUE THREAD

**Issue by 12345678902wsx** [MOIMOB/drinkable#425]
It might be nice to be able to add price/ingredient, so that you can view how much each cocktail costs you.

**Comment by anton-gustafsson** [comment]
Great idea! 

The ingredient prices could differ a lot for which country you are in.

Any ideas on how this could be solved are welcomed 😀

**Comment by sthyregod** [comment]
I'd suggest having a field on ingredients where you enter price and unit size from which the app calculates the amount that goes towards the drink. Maybe with a buffer to account for spills and the like.

**Comment by sthyregod** [comment]
\*insert random anti-stale message \*
