### ISSUE TITLE
Request: Add centiliters as a measurement option

### ISSUE THREAD

**Issue by BradNut** [MOIMOB/drinkable#434]
It would be nice if we could have metric cocktail measurements (centiliter) as a measurement option.

It's not that big of a deal given anyone can divide the milliliters by ten but cl is commonly used in recipes. Especially by the IBA (International Bartenders Association).

Thank you!

**Comment by anton-gustafsson** [comment]
Hi @BradNut! Great Idea.

Currently centiliter is available when you create your own cocktails. But from you text i assume you would like to see the current recipes in cl.

That could be an option under settings. If you selected Metric as your Measurement system you should also have the choice to pick between ml and cl.

**Comment by BradNut** [comment]
Hey @anton-gustafsson. Yes I meant being able to view current recipes in cl.

But I did not know that created cocktails could be created with cl so that is also good to know.

> That could be an option under settings. If you selected Metric as your Measurement system you should also have the choice to pick between ml and cl.

Yeah that is where I would think cl would fit best in the app. Would be great to get that added eventually! Thank you!

**Comment by anton-gustafsson** [comment]
@BradNut I agree that it would be a nice addition to the app. I will look into this

Thanks 🚀

**Comment by BradNut** [comment]
Nice! Thank you @anton-gustafsson !
