### ISSUE TITLE
German translation: Duplicate "Pfirsichlikör"

### ISSUE THREAD

**Issue by jensens** [MOIMOB/drinkable#457]
I downloaded the app and set it to German, as this is my native language. In the list of ingredients I found  a duplicate.
Now, usually such are a translation problems. 

Looking into https://github.com/MOIMOB/drinkable/blob/main/src/locales/de/ingredients.json I found its two English terms mapping to the same one in German. I would create a pull request, but I am not good enough with English terms of cocktail ingredients to be 100% sure.

Whats is exact the difference between peach-schnaps and peach-brandy? Both are translated to "Pfirsichlikör". 
Schnaps is a German word and natively means the non-sweat, clear, hi-alcohol (38+%) distilled kind. 
Likör in German is a very sweat, usually around 20% alcohol drink.

**Comment by anton-gustafsson** [comment]
Hi!
I understand the issue, but I don't have a great solution for it. I guess the german translation would fit perfectly for peach 
liqueur, but not quite right for peach brandy or peach schnapps.

What I understand is that brandy and schnapps are quite similar and share the same name in some languages. 

Do you have any suggestions for new translations? They should at least not share the same translation because that will end up confusing in the app 

Thank you!

**Comment by jensens** [comment]
Afyer using duckduckgo for a while I found his page https://thecocktailbird.com/peach-schnapps/ with the following differentiation:

> Peach Schnapps vs. Peach Brandy: What’s the Difference?

> Peach schnapps and peach brandy, while both peach-flavored spirits, have distinctive differences. Peach schnapps is a clear, sweet, peach-flavored liqueur made by blending peach juices with a neutral grain spirit, resulting in a strong, fruit-forward drink. It’s light, sweet, and has a very clear, bright peach flavor. 

> Peach brandy, on the other hand, is made by fermenting peaches and then distilling the juice. This results in a deeper, more complex flavor profile, with a rich, caramel-like sweetness and slightly smoky undertones. 

> The alcohol content also tends to be higher in peach brandy compared to peach schnapps drinks. In essence, while peach schnapps is often used in cocktails for its sweet, fruity flavor, peach brandy can be enjoyed straight or as a sophisticated addition to cocktails.

Given this is true, it is confusingly that peach-schnapps translates to "Pfirischlikör".  
And peach-brandy translates to "Pfirischschnaps".

Wow, language WTF ;-)

**Comment by anton-gustafsson** [comment]
Languages gets really confusing 😆 

Thank you for the PRs! 🚀

**Comment by anton-gustafsson** [comment]
Everything is merged and will be available in the next version of drinkable. I will close this issue now, but don't hesitate to open a new issue if you find other issues

Cheers 🍸
