### ISSUE TITLE
New York Sour different from IBA version

### ISSUE THREAD

**Issue by kidhanis** [MOIMOB/drinkable#467]
The New York Sour is tagged as an IBA cocktail, but [the recipe on the app](https://github.com/MOIMOB/drinkable/blob/20a4c5a4621260d4778395b07e72cbd7acbe4bfd/src/locales/en/instructions.json#L141) is different from the [IBA version](https://en.wikipedia.org/wiki/New_York_sour) which adds egg white into the mix.

**Comment by anton-gustafsson** [comment]
Thank you for reporting this! Will be fixed shortly
