### ISSUE TITLE
Is there some reference for cocktails?

### ISSUE THREAD

**Issue by Neriderc** [MOIMOB/drinkable#534]
I've been doing some casual reviewing of recipes, one thing I've noticed is the same recipe can vary a lot between sites.

For example, the After Dinner Cocktail specifies 60ml of lime juice. This is a lot more than other recipes I've seen.

[This one](http://inthespirit.co.uk/cocktails/view_cocktail.php?id=4) states 1 large dash.

[This one](https://www.barnonedrinks.com/drinks/a/after-dinner-cocktail-1-75.html) states the juice of one lime, and [this says](https://www.allrecipes.com/article/how-much-juice-in-one-lime/) 1 lime = 1 fl oz = 30ml.

[This one](https://www.easy-cocktail-recipes.net/v2/moods/cocktails/after-dinner-cocktail/) states 1cl lime juice (10ml).

Is there some cocktail authority that decides what counts as an "After Dinner Cocktail" (or anything else) or do we just do our best? I'd suggest this recipe is adjusted to have a lot less lime juice, perhaps 15ml.

I also have a bonus question: Is it ok if I alphabetically sort the data in cocktails.json, ingredients.json, and instructions.json? Or are you trying to keep these in the order in the cocktails-data.ts file that's sorted by ID?

**Comment by anton-gustafsson** [comment]
Hi! Thank you for the questions

I'll try to follow the IBA (International Bartenders Association) standard. But I guess many recipes needs to be adjusted. In the beginning I used data from TheCocktailDB but I had to do a lot of manually work and rearrange the data structure to be able to add new features for example Imperial/Metric conversion and better language support.

I do believe that the cocktail data can and should be updated to be the "best" version of itself

**Comment by anton-gustafsson** [comment]
For the translations files, I don't mind changing the order. When adding new cocktails I would probably find it easier to add it in the bottom but if there is some formatting command to sort in alphabetical order then its all good

**Comment by Neriderc** [comment]
> I'll try to follow the IBA (International Bartenders Association) standard. But I guess many recipes needs to be adjusted. In the beginning I used data from TheCocktailDB but I had to do a lot of manually work and rearrange the data structure to be able to add new features for example Imperial/Metric conversion and better language support.
> 
> I do believe that the cocktail data can and should be updated to be the "best" version of itself

Thanks for this. It looks like the IBA cocktails are published on their site here: https://iba-world.com/iba-official-cocktail-list/

I'm guessing there is some intellectual property stuff that comes into play here. According to [this](https://talesofthecocktail.org/intellectual-property-and-cocktails-what-everyone-should-know-about-protecting-their-cocktail-creations/), the recipe (I believe it means the ingredients and factual part of the method) can't be copyrighted, so if we write the recipe in our own words that should be fine.

According to that same source, cocktails can be patented, but anything older than 20 years should be safe.

I'll spend some time going through recipes and aligning them to IBA. I think it makes sense to use the exact recipe from IBA for IBA cocktails, since the "best" version is likely to be a matter of taste and IBA provides an authoritative source. 

However, for non-IBA cocktails, we can just adjust as needed. It looks like the After Dinner Cocktail isn't IBA, but if you're happy I'll update this to have 15ml of lime juice to put it in the general vicinity of the other recipes.

> For the translations files, I don't mind changing the order. When adding new cocktails I would probably find it easier to add it in the bottom but if there is some formatting command to sort in alphabetical order then its all good

Feel free to add to the bottom! My IDE keeps telling me I should sort it alphabetically, and provides an option to do it for me, and I thought it was a good idea.

However, the cocktails-data.ts file specifies the ID, and I think it makes sense to keep this in ID order. It will make it much easier to add new ones if we keep it this way.

**Comment by Neriderc** [comment]
I have a new question, but I'll close this and ask it in a new issue :slightly_smiling_face:
