### ISSUE TITLE
Can I add substitute ingredients for a specific cocktail?

### ISSUE THREAD

**Issue by Neriderc** [MOIMOB/drinkable#542]
I'm looking at the Alexander recipe. It states gin but the [IBA recipe uses cognac](https://iba-world.com/alexander/), so I think we should align this.

*However*, the IBA history section states that the cocktail was originally made with gin, but now the recipe uses cognac.

Some ingredients can have an alternative set (e.g. an alternative to lime juice is lime). Is it possible to do this for one specific cocktail, so I can have gin as an alternative in the Alexander recipe but it's not suggested for every recipe with cognac?

**Comment by anton-gustafsson** [comment]
I agree! We should change it to Cognac

Currently, the app only supports general substitutes like the lime/lime juice example

I just added a section to view the apps predefined list of substitutes. The next step is to allow users to create their own.

After that, I would look into cocktail specific  substitutes
