### ISSUE TITLE
Are Aperol Spritz and Spritz Veneziano the same drink?

### ISSUE THREAD

**Issue by Neriderc** [MOIMOB/drinkable#543]
The cocktails Aperol Spritz and Spritz Veneziano seem like pretty much the same thing. The Spritz Veneziano has smaller measurements than the Aperol Spritz but the ratios are basically the same.

Should we remove one?

Both are tagged as IBA, but are a bit different to the IBA listed recipe as the Drinkable ones have a lot more soda water than the "splash" that the IBA Spritz recipe calls for: https://iba-world.com/spritz/

Should we remove one and change the soda water to a splash for the other, so it aligns with the IBA recipe?

**Comment by anton-gustafsson** [comment]
Yes! I think we should remove one and update the other one to align with iba

Thank you for all of this 😀

**Comment by alaunay** [comment]
BTW, the aperol-spritz quantity are for *two* glasses, so I suspect that the ingredients should be divided by two, and the instructions should be modified for one glass only, given there is a calculator for 2 or more glasses in the app.

As per the quantity, the bottle of Aperol I've here gives volumes, not quantity:
- 3 vol of Prosecco
- 2 vol of Aperol
- 1 vol of sparkling water

My experiments with them gives then for one glass:
- 120 mL Prosecco
- 80 mL Aperol
- 40 mL sparkling water

So 240mL / glass.

Neither aperol-spritz nor spritz-veneziano seems to respect the volume indicated ;)

The IBA one uses a "splash" which is not a unit, according to the International System of Units ;)

If using the IBA one
- 90 mL Prosecco
- 60 mL Aperol
- 30 mL sparkling water

(so a "splash" is 30 mL, right ? :D)

Which gives a 180 mL / glass.

I personally prefer a bit more, given it's a "light" drink, that I serve in usually large glasses -- but still respecting the proportions.

I can propose a patch, once the almighty bartenders here tell me which quantities to use :cocktail:

**Comment by anton-gustafsson** [comment]
@alaunay Great input! Either way it is still better than what it is now. I think it would be easier to just follow IBA here. 

just for information: a splash in drinkable is 6ml when calculating the abv for cocktails 😄 

Would be great if you could create a pullrequest on this. Thank you

**Comment by alaunay** [comment]
Hmm, so the IBA does not "respect" the Aperol receipe...

An, the Aperol site lists one:

[Aperol Spritz](https://www.aperol.com/aperol-spritz-cocktail/)

Ingredients

    3 parts of Prosecco D.O.C. (9cl)
    2 parts of Aperol (6cl)
    1 splash of soda (3cl)
    1 slide of orange

They list a splash as 30 mL... :)
