### ISSUE TITLE
Find cocktails by ingredient

### ISSUE THREAD

**Issue by alaunay** [MOIMOB/drinkable#545]
Hello,

I ran into the following problem, I made a few cocktails using Prosecco, some using Ginger beer, and of course I still have some of both. So I tried looking if I could find a list of cocktails using these ingredients (not together... why not though), that I haven't found.

So answering the question: "I have prosecco, what can I do ?".

Even better: "I have prosecco, what can I do with the ingredients I also have ?"

(I can obviously grep in the source, but...)

Did I miss something, or is that something that does not exist ?

**Comment by anton-gustafsson** [comment]
The best way right now is to go to the cocktails tab and filter on a specific ingredient. This works for "All Cocktails" and "From Ingredients"

But here you can only filter on one ingredient at a time. Maybe a multiselect filter that would allow for any / all selection

**Comment by alaunay** [comment]
Oh wow ! I did not even saw the search bar and filters before... Well, case closed for the one ingredient case. It's amazing ! Thanks !

**Comment by alaunay** [comment]
Closing. Maybe creating another one for a multi-selection filter, but I'm very happy with the app as is. It's very low in the list of wanted things ;)
