### ISSUE TITLE
Profile don't work

### ISSUE THREAD

**Issue by Qreed213** [MOIMOB/drinkable#551]
I can't use more then 2 profiles/bars

Stock / my bar works
Secund profil/bar work
third bar/profil wil not aplye the chonge.

bar 2 & 3 are conected some how when removing 4b thetest user alsow gets wiped.

so for now be carefuld adding more profiles.

Cheers  :)

https://github.com/user-attachments/assets/51f73211-5f32-46f7-bd7f-8af08fd110b5

**Comment by anton-gustafsson** [comment]
Thank you!
