### ISSUE TITLE
Localizations (translation)

### ISSUE THREAD

**Issue by mYnDstrEAm** [MOIMOB/drinkable#84]
Please add translations so you can configure a language in the options.

You could auto-generate these, for example with some tool that uses DeepL (I don't know which tool would be best for generating the translated strings) or simply by copy pasting all of them at once into DeepL.

It wouldn't be important to translate the instructions, it would be sufficient if the ingredients were translated.

**Comment by anton-gustafsson** [comment]
That would be cool. I tried DeepL but my first impression was not that great.

**Comment by yephny** [comment]
The app would definitely get more popular if it was on F-Droid. With the user base growing, you'd also have people willing to do the translations, which is common in libre apps.

**Comment by anton-gustafsson** [comment]
I just created a request for packaging on F-Droid. Hope the process is smooth :)

**Comment by anton-gustafsson** [comment]
The app now uses i18n so all string values are stored in a translation.json file under a language directory. This will make it easy to add a new language.

[Example here](https://github.com/MOIMOB/drinkable/tree/main/src/locales/en)
